#!/usr/bin/bash

main() {
    # collect
    local acpi=$(acpi -b)
    local regex='Battery [0-9]: (.+), (.+)%, (.+) (remaining)?'
    [[ $acpi =~ $regex ]]

    local state="${BASH_REMATCH[1]}"
    local pow="${BASH_REMATCH[2]}"
    local time="${BASH_REMATCH[3]}"

    # format
    local prefix="☇ "
    # local prefix="⚡ "
    local value
    BG=$GRE
    FG=$BLA

    if [[ $state == "Discharging" ]]; then
        if (( $pow < 10 )); then
            color=$RED
        elif (( $pow < 25 )); then
            color=$YEL
        fi

        value="-${pow}% (${time})"
    else
        value="+${pow}%"
    fi

    #draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
