#!/usr/bin/bash

main() {
    local cpu=$(top -bn1 | grep "Cpu(s)" | \
                    sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | \
                    awk '{print 100 - $1"%"}')

    # format
    local prefix="<span font='FontAwesome'>\uf2db</span> "

    if (( $cpu > 90 )); then
        BG=$RED
        FG=$BLA
    elif (( $cpu > 75 )); then
        BG=$YEL
        FG=$BLA
    fi

    local value="${cpu}"

    # draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
