#!/usr/bin/bash

main() {
    # load
    read cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))

    sleep 0.5

    read cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))

    cpu="$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))"

    # temp
    local temp=$(sensors | awk '/temp1/ { print $2 }')
    temp=${temp:1}
    temp=${temp%????}

    # format
    local prefix="<span font='FontAwesome'>\uf2db</span> "

    if (( $temp > 80 )); then
        BG=$RED
        FG=$BLA
    elif (( $temp > 70 )); then
        BG=$YEL
        FG=$BLA
    fi

    # format
    if (( $cpu > 90 )); then
        BG=$RED
        FG=$BLA
    elif (( $cpu > 75 )); then
        BG=$YEL
        FG=$BLA
    fi

    local value="${cpu}% ${temp}°C"

    # draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
