#!/usr/bin/bash

main() {
    # collect
    local perc=$(df | awk '/\/dev\/sda2/ { print $5 }')
    local used=$(df -h | awk '/\/dev\/sda2/ { print $3 }')
    local total=$(df -h | awk '/\/dev\/sda2/ { print $2 }')
    local n="${perc%?}"

    local value="${prefix}${n}% ${used}/${total}"

    # format
    local prefix="<span font='FontAwesome'>\uf1c0</span> "
    # local prefix="⛁ "

    if (( $n > 95 )); then
        BG=$RED
    elif (( $n > 75 )); then
        FG=$BLA
        BG=$YEL
    fi

    # draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
