#!/usr/bin/bash

main() {
    local value

    # format
    local prefix="<span font='FontAwesome'>\uf11c</span> "

    case "$(xset -q | grep LED | awk '{ print $10 }')" in
        "00000000"|"00000001"|"00000002")
            value="en"
            ;;
        "00001000"|"00001001"|"00001002")
            value="no"

            BG=$MAG
            FG=$BLA
            ;;
        *)
            value="?"
            ;;
    esac

    value="${value} "

    # draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value}</span>"

    echo -e "${before}${text}${after}"
}
