#!/usr/bin/bash

main() {
    local kbd

    case "$(xset -q | grep LED | awk '{ print $10 }')" in
        "00000000"|"00000001"|"00000002")
            kbd="en"
            ;;
        "00001000"|"00001001"|"00001002")
            kbd="no"
            ;;
        *)
            kbd="?"
            ;;
    esac

    echo -e " ${kbd} "
}
