#!/usr/bin/bash

# In /etc/cron.hourly:
#!/bin/bash
#pacman -Sy 1>/dev/null 2>&1

main() {
    local prefix="ᗧ• "

    local pup="$(pacman -Qu | wc -l)"
    local c

    if (( "$pup" > 10 )); then
        c=$RED
    elif (( "$pup" > 0 )); then
        c=$YEL
    fi

    echo -e " ${prefix}${pup} "
    # echo -e "${c}"
}
