#!/usr/bin/bash

# In /etc/cron.hourly:
#!/bin/bash
#pacman -Sy 1>/dev/null 2>&1

main() {
    # collect
    local prefix="<span font='FontAwesome'>\uf17c</span> "
    local value="$(pacman -Qu | wc -l)"

    # format
    if (( "$value" > 10 )); then
        FG=$BLA
        BG=$RED
    elif (( "$value" > 0 )); then
        FG=$BLA
        BG=$YEL
    fi

    # draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
