#!/usr/bin/bash

main() {
    local temp=$(sensors | awk '/Package id 0/ { print $4 }')
    local s
    s=${temp:1}
    s=${s%????}
    local c

    if (( $s > 80 )); then
        c=$RED
    elif (( $s > 60 )); then
        c=$YEL
    fi

    echo -e "${s}°C "
    # echo -e "${c}"
}
