#!/usr/bin/bash

main() {
    # collect
    local value="$(date '+%H:%M:%S')"

    # format
    local prefix="<span font='FontAwesome'>\uf017</span> "
    # local prefix="🕐 "
    # local prefix="⧖ "

    FG=$BLA
    BG=$BLU

    # draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
