#!/usr/bin/bash

case $BLOCK_BUTTON in
    3) amixer -q sset Master toggle ;;
    4) amixer -q sset Master 8+ ;;
    5) amixer -q sset Master 8- ;;
esac

main() {
    # collect
    local info=$(amixer get Master)
    local level=$(echo ${info} | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
    local state=$(echo ${info} | tail -1 | sed 's/.*\[\(on\|off\)\].*/\1/')

    # format
    local prefix="♪ "
    local value

    if [[ "$state" == "off" ]]; then
        value="-"
        BG=$YEL
        FG=$BLA
    else
        value="${level}"
    fi

    #draw
    local before="<span color='${BG}' bgcolor='${BLA}'></span>"
    local after="<span color='${BLA}' bgcolor='${BG}'></span>"

    local text="<span color='${FG}' bgcolor='${BG}'> ${prefix}${value} </span>"

    echo -e "${before}${text}${after}"
}
