#!/usr/bin/bash

# powerline glyphs
# 
# 
# 
# 

readonly DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DEV=$1

readonly WHI='#f6f3e8'
readonly GRA='#aaaaaa'
readonly BLA='#222222'
readonly RED='#e5786d'
readonly YEL='#ffe161'
readonly GRE='#cae682'
readonly BLU='#5283d7'

# default colors
FG=$GRA
BG=$BLA

# check arguments
if [ "$#" -ne 1 ]
then
    echo "usage: ${0} <dev>"
    exit 1
fi

# check if file exists and run
if [ ! -e $DIR/$DEV ]
then
    echo "block '$DEV' not found"
    exit 1
else
    . $DIR/$DEV

    echo -e "$(main)"
fi
